docker:
  image: g4s8/rultor-jdk11:alpine3.10
architect:
  - amihaiemil
assets:
  settings.xml: "amihaiemil/maven#settings.xml"
  pubring.gpg: "amihaiemil/maven#pubring.gpg"
  secring.gpg: "amihaiemil/maven#secring.gpg"
  linguin-ai-token.txt: "amihaiemil/maven#linguin-ai-token.txt"
env:
  JAVA_HOME: /usr/lib/jvm/java-11-openjdk
merge:
  script: |-
    mvn clean install -Pcheckstyle,itcases
deploy:
  script: |-
    echo 'Nothing to deploy'
    exit -1
release:
  script: |-
    chmod +x ./release.sh
    ./release.sh
